osx_image: xcode10.1
language: objective-c
xcode_workspace: SafeNest.xcworkspace
xcode_scheme: SafeNest
xcode_sdk: iphonesimulator11.2

before_install:
  - gem install cocoapods --pre
  - gem install slather xcpretty
  - pod repo update

script:
  - set -o pipefail && xcodebuild clean test -sdk iphonesimulator -workspace SafeNest.xcworkspace -scheme SafeNest -destination 'platform=iOS Simulator,name=iPhone 7' | xcpretty

after_success: slather
